project:
  type: website
  output-dir: _output
  render:
    - "*.qmd"
    - "!README.md"

website:
  title: "Psychology at Goldsmiths"
  navbar:
    background: "#111111"
    foreground: "#ffffff"
    logo: "images/goldsmiths-logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: Applicant.qmd
        text: Applicant Day
      - href: contact.qmd
        text: Contact

format:
  revealjs:
    theme: [default, presentation.scss]
    slide-number: true
    chalkboard: false
    preview-links: auto
    logo: "images/goldsmiths-logo.png"
    footer: "Psychology at Goldsmiths | Where science meets creativity"
    transition: slide
    background-transition: fade
    highlight-style: github
    code-line-numbers: false
    controls: true
    progress: true
    history: true
    hash: true
    center: false
    width: 1280
    height: 720
    margin: 0.2
    link-external-newwindow: true
    embed-resources: true

